### ISSUE TITLE
About the SQL depth

### ISSUE THREAD

**Issue by wangjiyuan9** [kieran514/baseboostdepth#2]
Hi, I'm excited that you have published your new work.
 But, have you ever noticed that the SQL depth, has a different training split?
Actually, about 2month ago, I tried SQL depth baseline with the traditional Zhou split, and the training result was poor.
So I'm really amazed that you got the correct result with the traditional Zhou split.
Can you give me some explanation about this issue?
https://github.com/hisfog/SfMNeXt-Impl/issues/40#issue-2242655720

**Comment by kieran514** [comment]
Thank you for your interest in our work. We also noticed an inability to recreate SQLDepth's results from scratch. This exact GitHub issue was observed after our submission. The reason we matched and improved upon their results is because we used SQLDepth's pre-trained weights as a starting point and then applied our boosting method from the paper. We demonstrate that our work has great validity with other backbones like MonoViT and Monodepth2, which can be recreated from scratch. However, we could not start from scratch with SQLDepth.

We assumed we might have made an error when trying to recreate SQLDepth and trusted that the authors of SQLDepth (AAAI'24) provided truthful results, so we used their state-of-the-art backbone (pre-trained weights) to show that we could improve it. However, due to this thread, I do not necessarily trust SQLDepth's work anymore.

Rest assured, our work can be recreated, and we did use the experimental split stated in our paper. Our paper is backbone agnostic and hence can be applied to any past or new depth backbone. 

I hope this helps.
